[package]
name = "leavedesk"
version = "0.1.0"
description = "LeaveDesk - Staff Leave Management"

[[module]]
name = "static-web-server"
source = "wasmer/static-web-server@1"
abi = "wasi"

[fs]
"/public" = "public"

[[command]]
name = "script"
module = "static-web-server"
runner = "wasi"

[command.annotations.wasi]
main-args = ["-w", "/public", "--port", "3000"]
